In [1]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

import warnings
warnings.filterwarnings('ignore')

In [6]:
df_lending = pd.read_csv(Path("Resources/lending_data.csv"))
df_lending.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  loan_status  
0                 1       22800            0  
1                 0       13600            0  
2                 0       16100            0  
3                 1       22700            0  
4                 1       23000            0

In [15]:
y = df_lending['loan_status']
X = df_lending.drop(['loan_status'], axis = 1)

In [16]:
y

0        0
1        0
2        0
3        0
4        0
        ..
77531    1
77532    1
77533    1
77534    1
77535    1
Name: loan_status, Length: 77536, dtype: int64

In [17]:
X

loan_size  interest_rate  borrower_income  debt_to_income  \
0        10700.0          7.672            52800        0.431818   
1         8400.0          6.692            43600        0.311927   
2         9000.0          6.963            46100        0.349241   
3        10700.0          7.664            52700        0.430740   
4        10800.0          7.698            53000        0.433962   
...          ...            ...              ...             ...   
77531    19100.0         11.261            86600        0.653580   
77532    17700.0         10.662            80900        0.629172   
77533    17600.0         10.595            80300        0.626401   
77534    16300.0         10.068            75300        0.601594   
77535    15600.0          9.742            72300        0.585062   

       num_of_accounts  derogatory_marks  total_debt  
0                    5                 1       22800  
1                    3                 0       13600  
2                    3                 0       16100  
3                    5                 1       22700  
4                    5                 1       23000  
...                ...               ...         ...  
77531               12                 2       56600  
77532               11                 2       50900  
77533               11                 2       50300  
77534               10                 2       45300  
77535                9                 2       42300  

[77536 rows x 7 columns]

In [18]:
# Check the balance of our target values
y.value_counts()

0    75036
1     2500
Name: loan_status, dtype: int64

In [32]:
# Import the train_test_learn module
from sklearn.model_selection import train_test_split

# Split the data using train_test_split
# Assign a random_state of 1 to the function
# training_features, testing_features, training_targets, testing_targets = train_test_split(X, y, random_state = 1)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 1)

In [38]:
# Import the LogisticRegression module from SKLearn
from sklearn.linear_model import LogisticRegression

# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
lrm = LogisticRegression(random_state = 1)

# Fit the model using training data
lr_model = lrm.fit(X_train, y_train)
lr_model

LogisticRegression(random_state=1)

In [39]:
# Make a prediction using the testing data
# training_predictions = lrm.predict(X_train)
testing_predictions = lrm.predict(X_test)
testing_predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [42]:
# Print the balanced_accuracy score of the model

balanced_accuracy_score(y_test, testing_predictions)

0.9520479254722232

In [47]:
# Generate a confusion matrix for the model
training_matrix = confusion_matrix(y_train, training_predictions)
training_matrix

array([[55994,   277],
       [  181,  1700]], dtype=int64)

In [50]:
# Print the classification report for the model
training_report = classification_report_imbalanced(y_train, training_predictions)
print(training_report)

                   pre       rec       spe        f1       geo       iba       sup

          0       1.00      1.00      0.90      1.00      0.95      0.91     56271
          1       0.86      0.90      1.00      0.88      0.95      0.89      1881

avg / total       0.99      0.99      0.91      0.99      0.95      0.91     58152



In [51]:
# Import the RandomOverSampler module form imbalanced-learn
from imblearn.over_sampling import RandomOverSampler

# Instantiate the random oversampler model
# # Assign a random_state parameter of 1 to the model
random_oversampler = RandomOverSampler(random_state=1)


# Fit the original training data to the random_oversampler model
X_resampled, y_resampled = random_oversampler.fit_resample(X_train, y_train)

In [57]:
# Count the distinct values of the resampled labels data
y_resampled.value_counts()

0    56271
1    56271
Name: loan_status, dtype: int64

In [70]:
# Instantiate the Logistic Regression model
# Assign a random_state parameter of 1 to the model
lrm_2 = LogisticRegression(random_state = 1)

# Fit the model using the resampled training data
lr_model_2 = lrm_2.fit(X_resampled, y_resampled)
lr_model_2

# Make a prediction using the testing data
testing_predictions_2 = lrm_2.predict(X_resampled)
testing_predictions_2

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [77]:
# Print the balanced_accuracy score of the model 
balanced_accuracy_score(y_resampled, testing_predictions_2)

0.9947308560359689

In [79]:
# Generate a confusion matrix for the model
training_matrix_2 = confusion_matrix(y_resampled, testing_predictions_2)
training_matrix

array([[55994,   277],
       [  181,  1700]], dtype=int64)

In [80]:
# Print the classification report for the model
training_report_2 = classification_report_imbalanced(y_resampled, testing_predictions_2)
print(training_report_2)

                   pre       rec       spe        f1       geo       iba       sup

          0       0.99      0.99      0.99      0.99      0.99      0.99     56271
          1       0.99      0.99      0.99      0.99      0.99      0.99     56271

avg / total       0.99      0.99      0.99      0.99      0.99      0.99    112542

